trigger:
- main

pool:
  name: Azure Pipelines
  vmImage: 'vs2017-win2016'

steps:
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: 'Use Terraform latest'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : INIT'
  inputs:
    backendServiceArm: 'ngapp-SPN'
    backendAzureRmResourceGroupName: 'NG_App-infra'
    backendAzureRmStorageAccountName: ngapp01tstate
    backendAzureRmContainerName: tstate
    backendAzureRmKey: '{2a/EjyAxIlQ/fgE2eE81n+z0pkQm45LFLkQoVVJpTXPA64+ntla+P39eJ1LQlQLHK3OSle5RMk//+AStg+68JQ==}"'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : PLAN'
  inputs:
    command: plan
    environmentServiceNameAzureRM: 'ngapp-SPN'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : VAL & APPLY'
  inputs:
    command: apply
    environmentServiceNameAzureRM: 'ngapp-SPN'
